### ISSUE TITLE
screen shot

### ISSUE THREAD

**Issue by suzuki-shunsuke** [aquaproj/aquaproj.github.io#119]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/13323303/176574096-d29955c6-3ed0-41ac-8b00-e72167e0418e.png">

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176577017-6573ac61-c124-40f8-8bfe-01bec8e59e4d.png)

![image](https://user-images.githubusercontent.com/13323303/176577312-31323496-6b06-4dbf-9d4b-b41fa5626dc5.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176579462-e843b334-86a0-4b16-88ab-e39b8fbfa0a9.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176579880-06b35bc2-da2f-422d-a900-74b4f09c08d5.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176581178-c8cc116f-cc90-4719-a693-4b08cf526734.png)

**Comment by suzuki-shunsuke** [comment]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/13323303/176581983-db7e4324-a319-4eaf-ab62-01a833018b52.png">

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/13323303/176582033-f35f9062-f611-4e0f-8974-b47178ccae98.png">

--

<img width="826" alt="image" src="https://user-images.githubusercontent.com/13323303/176582094-a877de4b-8be8-410b-b65d-7ce9be1d649e.png">

**Comment by suzuki-shunsuke** [comment]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/13323303/176581983-db7e4324-a319-4eaf-ab62-01a833018b52.png">

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/13323303/176582552-438c02a7-d22f-4179-a254-ea3aba964f16.png">

--

<img width="817" alt="image" src="https://user-images.githubusercontent.com/13323303/176582627-44f27c48-213b-44da-b18f-d4d482ef2f56.png">

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176583057-d4430e14-3d42-45e9-914f-77adedcf4975.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176584418-c6a4adca-e4d8-45aa-98b0-6ae3b543b007.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176584607-951eefc0-572b-48eb-84f7-b2c17efb5cd4.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176584746-3ec582d7-9cbe-41fe-ab1a-1b26e1436518.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176584915-f8f99736-6553-4f1f-b0ef-811df90f5ccf.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176585183-b8616482-5e3b-4f99-be98-6e7d752c5dbc.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176597821-68b0997d-392a-4b16-bf4c-31f63ab752c9.png)

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/176598973-2e71d83c-3cbc-4ec3-a315-05070a99bb75.png)

**Comment by suzuki-shunsuke** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/13323303/178093916-fe6ccccd-d313-43ad-bcd1-e456db4637c2.png">

**Comment by suzuki-shunsuke** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/13323303/178093930-6adc8928-96e4-425a-9741-a48aac6ccf75.png">

**Comment by suzuki-shunsuke** [comment]
![image](https://user-images.githubusercontent.com/13323303/194790198-a2da67dd-2d72-43ae-bf00-a0c7be9791b1.png)

--

![image](https://user-images.githubusercontent.com/13323303/194790358-2ec51331-52e1-4451-86f6-cb74c2a852e7.png)

**Comment by suzuki-shunsuke** [comment]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/13323303/212663990-e72a3ae4-2c23-48e8-94dc-1ae74f8a80a0.png">

**Comment by suzuki-shunsuke** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/13323303/212687486-67239304-4cd6-45d7-bc72-6788f60c7d49.png">

**Comment by suzuki-shunsuke** [comment]
![aqua-strict-version-control drawio](https://user-images.githubusercontent.com/13323303/221387356-95d9d9fd-6c19-4015-830c-63d86a4a38e0.png)

**Comment by Quantumleapz6** [comment]
Looks great! Keep up the good work. I have a AquaCoin project I would like to start. It's a token that represents water rights and futures for different bodies of water and brands and it would be represented in the commodities market or bond market.
