### ISSUE TITLE
Implement Prettier , Husky and Eslint for Codebase Improvement

### ISSUE THREAD

**Issue by Tholkappiar** [aquaproj/aquaproj.github.io#639]
**Feature request**
I propose adding Husky , Prettier  and Eslint to enhance the code quality in this repository.

**Pros**
Husky ensures code quality by running scripts before Git commits and pushes, and Prettier automates code formatting for consistent style.

**Additional context
Steps:**

- Install Husky , eslint into project dependencies.
- Set up Husky to run Prettier on pre-commit and pre-push hooks.

_PS :_ **I'm eager to work on this. Please assign this issue to me.**

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I don't like pre commit hooks because sometimes they are slow and annoying.
We don't have the motivation to introduce them for now.
